version: 1.0.0.{build}
platform: x64

skip_branch_with_pr: false

install:
  - ps:(New-Object Net.WebClient).DownloadFile('https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip', 'C:/wix/wix-binaries.zip')
  - ps: cd C:/wix
  - ps: unzip wix-binaries.zip
  - ps: [Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";C:\wix", "Machine")

build_script:
  - cmd: make
  - cmd: make pkg-slim

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/%SIGNPATH_ORGANIZATION_ID%/Integrations/AppVeyor?ProjectSlug=%SIGNPATH_PROJECT_SLUG%&SigningPolicySlug=%SIGNPATH_SIGNING_POLICY_SLUG%&ArtifactConfigurationSlug=%ARTIFACT_CONFIGURATION_SLUG%
    authorization: 'Bearer %SIGNPATH_CI_USER_TOKEN%'
