environment:

  MSVS_VERSION: 2015

  matrix:
    - PYTHON: "C:\\Python35-x64"
      DISTUTILS_USE_SDK: "1"

platform:
  - x64

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install -r requirements.txt"

build_script:
  - ps: "cd kstream"
  - "python setup.py build_ext --inplace"

test_script:
  - py.test tests/"

artifacts:
  - path: dist\*
