version: 1.0.0.{build}
platform: x64

skip_branch_with_pr: false

install:
  - mkdir C:\wix
  - ps: Invoke-WebRequest https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile C:\wix\wix-binaries.zip
  - cd C:\wix
  - unzip wix-binaries.zip
  - cd C:\projects\fibratus

environment:
  VERSION: 0.0.0

build_script:
  - cmd: make rsrc
  - cmd: make
  - cmd: set PATH=%PATH%;C:\wix
  - cmd: make pkg-slim

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/%SIGNPATH_ORGANIZATION_ID%/Integrations/AppVeyor?ProjectSlug=%SIGNPATH_PROJECT_SLUG%&SigningPolicySlug=%SIGNPATH_SIGNING_POLICY_SLUG%&ArtifactConfigurationSlug=%ARTIFACT_CONFIGURATION_SLUG%
    authorization: 'Bearer %SIGNPATH_CI_USER_TOKEN%'
