environment:

  global:
    CMD_IN_ENV: "cmd /C run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - "pip install -r requirements.txt"

build_script:
  - ps: "cd kstream"
  - "%CMD_IN_ENV% python setup.py build_ext --inplace"

test_script:
  - py.test tests/"

artifacts:
  - path: dist\*
