type: map
mapping:

  image_meta:
    type: map
    mapping:
      enabled:
        type: bool
        required: True
      imports:
        type: bool
      file_info:
        type: bool

  skips:
    type: map
    required: True
    mapping:
      images:
        type: seq
        sequence:
          - type: str

  output:
    type: seq
    required: True
    sequence:
      - type: map
        mapping:

          console:
            type: map
            mapping:
              format:
                type: str
                enum: ['pretty', 'json']

          amqp:
            type: map
            mapping:
              host:
                type: str
              port:
                type: int
              username:
                type: str
              password:
                type: str
              vhost:
                type: str
              exchange:
                type: str
                required: True
              routingkey:
                type: str
                required: True

          smtp:
            type: map
            mapping:
              host:
                type: str
                required: True
              port:
                type: int
              password:
                type: str
              from:
                type: str
                pattern: .+@.+
              to:
                type: seq
                sequence:
                  - type: str
                    pattern: .+@.+

          elasticsearch:
            type: map
            mapping:
              hosts:
                type: seq
                required: True
                sequence:
                  - type: str
                    required: True
              index:
                type: str
                required: True
              index_type:
                type: str
                enum: ['fixed', 'daily']
              daily_index_format:
                type: str
              document:
                type: str
                required: True
              bulk:
                type: bool
              username:
                type: str
              password:
                type: str
              ssl:
                type: bool

          fs:
            type: map
            mapping:
              path:
                type: str
                required: True
              mode:
                type: str
                enum: ['r', 'w', 'x', 'a', 'r+', 'w+']
              format:
                type: str
                enum: ['json']

  binding:
    type: seq
    sequence:
      - type: map
        mapping:

          yara:
            type: map
            mapping:
              path:
                type: str
                required: True


