name: master

on:
  push:
    branches:
      - master
    paths-ignore: 
      - "README.md"
      - "CONTRIBUTING.md"
      - "docs/**"

env:
  BUILD_TAGS: "kcap,filament,yara"
           
jobs:
  build:
      runs-on: windows-latest
      steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
           go-version: 1.15.x
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            git
      - name: Install libyara
        shell: msys2 {0}           
        run: |
            git clone https://github.com/VirusTotal/yara.git
            cd yara
            autoreconf -fiv
            ./configure --host=x86_64-w64-mingw32
            make install
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        shell: bash
        run: |
          export PATH="c/msys64/mingw64/bin:/c/Strawberry/perl/bin:$PATH"
          export PKG_CONFIG_PATH=$(pwd)
          ln -s C:/hostedtoolcache/windows/Python/3.7.9/x64 C:/Python37
          go build -ldflags "-s -w -X github.com/rabbitstack/fibratus/cmd/fibratus/app.commit=$GITHUB_SHA" \
                   -tags $BUILD_TAGS -o ./cmd/fibratus/fibratus.exe ./cmd/fibratus
      - name: Lint
        shell: bash
        run: |
          go get -v -u golang.org/x/lint/golint
          go list ./... | xargs -L1 $USERPROFILE/go/bin/golint -set_exit_status
